name: Java CI

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        gradle:
        - 6.0.1
        - 5.6.4
        - 5.5.1
        - 5.4.1
        - 5.3.1
        - 5.2.1
        - 5.1.1
        - 4.10.3
        - 4.9
        - 4.8.1
        - 4.7

    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: check jacocoFullReport
        gradle-version: ${{ matrix.gradle }}
